require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MacApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'Firebase/Analytics'

  # pod 'Firebase/Messaging'

  # pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  # pod 'react-native-apple-authentication', :path => '../node_modules/react-native-apple-authentication'

  # pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  # pod 'react-native-firebase-push-notifications', :path => '../node_modules/react-native-firebase-push-notifications'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  target 'MacAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end